### ISSUE TITLE
.

### ISSUE THREAD

**Issue by YieldRay** [qingzhenyun/qingzhenyun-docs#3]
.

**Comment by Crazy-White** [comment]
> 
> 
> **说实话真没找到怎么下载**

**Comment by zzzhr1990** [comment]
https://github.com/zzzhr1990/qingzhenyun-api-doc/blob/master/v2/000.020.%E7%94%A8%E6%88%B7%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F/000.200.%E4%B8%8B%E8%BD%BD%E6%96%87%E4%BB%B6.md

**Comment by zzzhr1990** [comment]
> .

https://github.com/zzzhr1990/qingzhenyun-api-doc/blob/master/v2/000.020.%E7%94%A8%E6%88%B7%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F/000.200.%E4%B8%8B%E8%BD%BD%E6%96%87%E4%BB%B6.md
